/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package login.spring.boot;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
//    @Test public void testAppHasAGreeting() {
//        LoginApplication classUnderTest = new LoginApplication();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//    }
}
